name: Magna-World
version: 0.11.0
author: MoriGM
api-version: 1.19

depend: [ Magna ]

main: de.morigm.magnaworld.Main

commands:
      mwcreate:
      mwtp:
      mwdelete:
      mwlist:
      mwimport: