name: Magna-World
version: 0.9.0
author: MoriGM
api-version: 1.16

loadbefore: [Magna]

main: de.morigm.magnaworld.Main

commands:
      mwcreate:
      mwtp:
      mwdelete:
      mwlist:
      mwimport: